name: Setup boilerplate
inputs:
  renderer-template:
    description: Define what vite template should be used to create renderer in case if renderer package doesn't exist
    required: false
    default: ''


runs:
  using: "composite"
  steps:
    - if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        Xvfb :99 -screen 0 1280x960x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 'latest'

    - name: Check if renderer directory exists
      id: check-renderer
      run: >-
        if [ -d "packages/renderer" ]; then
          echo "RENDERER_EXIST=true" >> $GITHUB_OUTPUT
        else
          echo "RENDERER_EXIST=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - run: |
        bun run create-renderer -- -- --template ${{inputs.renderer-template}}
        bun run integrate-renderer
      shell: bash
      if: inputs.renderer-template != '' && steps.check-renderer.outputs.RENDERER_EXIST == 'false'

    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          **/node_modules
        key: bun-${{ runner.os }}-${{ inputs.renderer-template }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          bun-${{ runner.os }}-${{ inputs.renderer-template }}-

    - name: Install Dependencies
      run: bun install --no-save
      shell: bash
